
image: python:3.8

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest

build:
  stage: build
  script:
    - docker build -t my-docker-repo/webapp .

deploy:
  stage: deploy
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
    - docker push my-docker-repo/webapp
